os: linux

language: go

go:
  - 1.18.2

services:
  - postgresql
  - docker

addons:
  sonarcloud:
    organization: "bennogreg"
    token:
      secure: "cafe205e38ef51ae859c2d88b7dade407b30881d"

script:
  - sonar-scanner -X
  - go test -v
