os: linux

language: go

go:
  - 1.18.2

services:
  - postgresql
  - docker

addons:
  sonarcloud:
    organization: "bennogreg"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
  - go test -v
